// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: scenario.proto

package scenario

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeTypes int32

const (
	NodeTypes_START     NodeTypes = 0
	NodeTypes_MESSAGE   NodeTypes = 1
	NodeTypes_FORM      NodeTypes = 2
	NodeTypes_CONDITION NodeTypes = 3
	NodeTypes_VARIABLE  NodeTypes = 4
	NodeTypes_HTML      NodeTypes = 5
)

// Enum value maps for NodeTypes.
var (
	NodeTypes_name = map[int32]string{
		0: "START",
		1: "MESSAGE",
		2: "FORM",
		3: "CONDITION",
		4: "VARIABLE",
		5: "HTML",
	}
	NodeTypes_value = map[string]int32{
		"START":     0,
		"MESSAGE":   1,
		"FORM":      2,
		"CONDITION": 3,
		"VARIABLE":  4,
		"HTML":      5,
	}
)

func (x NodeTypes) Enum() *NodeTypes {
	p := new(NodeTypes)
	*p = x
	return p
}

func (x NodeTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_scenario_proto_enumTypes[0].Descriptor()
}

func (NodeTypes) Type() protoreflect.EnumType {
	return &file_scenario_proto_enumTypes[0]
}

func (x NodeTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeTypes.Descriptor instead.
func (NodeTypes) EnumDescriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{0}
}

// Message Node
type MessageNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeType NodeTypes            `protobuf:"varint,2,opt,name=nodeType,proto3,enum=scenario.NodeTypes" json:"nodeType,omitempty"`
	FormData *MessageNodeFormData `protobuf:"bytes,3,opt,name=formData,proto3" json:"formData,omitempty"`
}

func (x *MessageNode) Reset() {
	*x = MessageNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scenario_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageNode) ProtoMessage() {}

func (x *MessageNode) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageNode.ProtoReflect.Descriptor instead.
func (*MessageNode) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{0}
}

func (x *MessageNode) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MessageNode) GetNodeType() NodeTypes {
	if x != nil {
		return x.NodeType
	}
	return NodeTypes_START
}

func (x *MessageNode) GetFormData() *MessageNodeFormData {
	if x != nil {
		return x.FormData
	}
	return nil
}

// Message Node's form data
type MessageNodeFormData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsInvalid bool   `protobuf:"varint,1,opt,name=isInvalid,proto3" json:"isInvalid,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text      string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *MessageNodeFormData) Reset() {
	*x = MessageNodeFormData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scenario_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageNodeFormData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageNodeFormData) ProtoMessage() {}

func (x *MessageNodeFormData) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageNodeFormData.ProtoReflect.Descriptor instead.
func (*MessageNodeFormData) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{1}
}

func (x *MessageNodeFormData) GetIsInvalid() bool {
	if x != nil {
		return x.IsInvalid
	}
	return false
}

func (x *MessageNodeFormData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MessageNodeFormData) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Form Node
type FormNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeType NodeTypes         `protobuf:"varint,2,opt,name=nodeType,proto3,enum=scenario.NodeTypes" json:"nodeType,omitempty"`
	FormData *FormNodeFormData `protobuf:"bytes,3,opt,name=formData,proto3" json:"formData,omitempty"`
}

func (x *FormNode) Reset() {
	*x = FormNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scenario_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormNode) ProtoMessage() {}

func (x *FormNode) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormNode.ProtoReflect.Descriptor instead.
func (*FormNode) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{2}
}

func (x *FormNode) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FormNode) GetNodeType() NodeTypes {
	if x != nil {
		return x.NodeType
	}
	return NodeTypes_START
}

func (x *FormNode) GetFormData() *FormNodeFormData {
	if x != nil {
		return x.FormData
	}
	return nil
}

// Form Node's form data
type FormNodeFormData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsInvalid bool   `protobuf:"varint,1,opt,name=isInvalid,proto3" json:"isInvalid,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *FormNodeFormData) Reset() {
	*x = FormNodeFormData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scenario_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormNodeFormData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormNodeFormData) ProtoMessage() {}

func (x *FormNodeFormData) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormNodeFormData.ProtoReflect.Descriptor instead.
func (*FormNodeFormData) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{3}
}

func (x *FormNodeFormData) GetIsInvalid() bool {
	if x != nil {
		return x.IsInvalid
	}
	return false
}

func (x *FormNodeFormData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// Variable Node
type VariableNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeType NodeTypes             `protobuf:"varint,2,opt,name=nodeType,proto3,enum=scenario.NodeTypes" json:"nodeType,omitempty"`
	FormData *VariableNodeFormData `protobuf:"bytes,3,opt,name=formData,proto3" json:"formData,omitempty"`
}

func (x *VariableNode) Reset() {
	*x = VariableNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scenario_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VariableNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableNode) ProtoMessage() {}

func (x *VariableNode) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableNode.ProtoReflect.Descriptor instead.
func (*VariableNode) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{4}
}

func (x *VariableNode) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VariableNode) GetNodeType() NodeTypes {
	if x != nil {
		return x.NodeType
	}
	return NodeTypes_START
}

func (x *VariableNode) GetFormData() *VariableNodeFormData {
	if x != nil {
		return x.FormData
	}
	return nil
}

// Variable Node's form data
type VariableNodeFormData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsInvalid  bool   `protobuf:"varint,1,opt,name=isInvalid,proto3" json:"isInvalid,omitempty"`
	Title      string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	VariableID string `protobuf:"bytes,3,opt,name=variableID,proto3" json:"variableID,omitempty"`
}

func (x *VariableNodeFormData) Reset() {
	*x = VariableNodeFormData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scenario_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VariableNodeFormData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableNodeFormData) ProtoMessage() {}

func (x *VariableNodeFormData) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableNodeFormData.ProtoReflect.Descriptor instead.
func (*VariableNodeFormData) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{5}
}

func (x *VariableNodeFormData) GetIsInvalid() bool {
	if x != nil {
		return x.IsInvalid
	}
	return false
}

func (x *VariableNodeFormData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VariableNodeFormData) GetVariableID() string {
	if x != nil {
		return x.VariableID
	}
	return ""
}

// Condition Node
type ConditionNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeType NodeTypes              `protobuf:"varint,2,opt,name=nodeType,proto3,enum=scenario.NodeTypes" json:"nodeType,omitempty"`
	FormData *ConditionNodeFormData `protobuf:"bytes,3,opt,name=formData,proto3" json:"formData,omitempty"`
}

func (x *ConditionNode) Reset() {
	*x = ConditionNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scenario_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConditionNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionNode) ProtoMessage() {}

func (x *ConditionNode) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionNode.ProtoReflect.Descriptor instead.
func (*ConditionNode) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{6}
}

func (x *ConditionNode) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConditionNode) GetNodeType() NodeTypes {
	if x != nil {
		return x.NodeType
	}
	return NodeTypes_START
}

func (x *ConditionNode) GetFormData() *ConditionNodeFormData {
	if x != nil {
		return x.FormData
	}
	return nil
}

// Condition Node's form data
type ConditionNodeFormData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsInvalid bool   `protobuf:"varint,1,opt,name=isInvalid,proto3" json:"isInvalid,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *ConditionNodeFormData) Reset() {
	*x = ConditionNodeFormData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scenario_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConditionNodeFormData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionNodeFormData) ProtoMessage() {}

func (x *ConditionNodeFormData) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionNodeFormData.ProtoReflect.Descriptor instead.
func (*ConditionNodeFormData) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{7}
}

func (x *ConditionNodeFormData) GetIsInvalid() bool {
	if x != nil {
		return x.IsInvalid
	}
	return false
}

func (x *ConditionNodeFormData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// HTML Node
type HTMLNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NodeType NodeTypes         `protobuf:"varint,2,opt,name=nodeType,proto3,enum=scenario.NodeTypes" json:"nodeType,omitempty"`
	FormData *HTMLNodeFormData `protobuf:"bytes,3,opt,name=formData,proto3" json:"formData,omitempty"`
}

func (x *HTMLNode) Reset() {
	*x = HTMLNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scenario_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTMLNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTMLNode) ProtoMessage() {}

func (x *HTMLNode) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTMLNode.ProtoReflect.Descriptor instead.
func (*HTMLNode) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{8}
}

func (x *HTMLNode) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HTMLNode) GetNodeType() NodeTypes {
	if x != nil {
		return x.NodeType
	}
	return NodeTypes_START
}

func (x *HTMLNode) GetFormData() *HTMLNodeFormData {
	if x != nil {
		return x.FormData
	}
	return nil
}

// HTML Node's form data
type HTMLNodeFormData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsInvalid  bool   `protobuf:"varint,1,opt,name=isInvalid,proto3" json:"isInvalid,omitempty"`
	Title      string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	HtmlString string `protobuf:"bytes,3,opt,name=htmlString,proto3" json:"htmlString,omitempty"`
}

func (x *HTMLNodeFormData) Reset() {
	*x = HTMLNodeFormData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scenario_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTMLNodeFormData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTMLNodeFormData) ProtoMessage() {}

func (x *HTMLNodeFormData) ProtoReflect() protoreflect.Message {
	mi := &file_scenario_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTMLNodeFormData.ProtoReflect.Descriptor instead.
func (*HTMLNodeFormData) Descriptor() ([]byte, []int) {
	return file_scenario_proto_rawDescGZIP(), []int{9}
}

func (x *HTMLNodeFormData) GetIsInvalid() bool {
	if x != nil {
		return x.IsInvalid
	}
	return false
}

func (x *HTMLNodeFormData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HTMLNodeFormData) GetHtmlString() string {
	if x != nil {
		return x.HtmlString
	}
	return ""
}

var File_scenario_proto protoreflect.FileDescriptor

var file_scenario_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x22, 0x89, 0x01, 0x0a, 0x0b, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x08, 0x6e, 0x6f,
	0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x73,
	0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x66,
	0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x4e, 0x6f, 0x64, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x66, 0x6f,
	0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x22, 0x5d, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x4e, 0x6f, 0x64, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a,
	0x09, 0x69, 0x73, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x69, 0x73, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x83, 0x01, 0x0a, 0x08, 0x46, 0x6f, 0x72, 0x6d, 0x4e, 0x6f,
	0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x2f, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f,
	0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x08, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x22, 0x46, 0x0a, 0x10, 0x46,
	0x6f, 0x72, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1c, 0x0a, 0x09, 0x69, 0x73, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x22, 0x8b, 0x01, 0x0a, 0x0c, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65,
	0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69,
	0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x08, 0x6e, 0x6f, 0x64,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72,
	0x69, 0x6f, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x46,
	0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x6a, 0x0a, 0x14, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x64,
	0x65, 0x46, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x49,
	0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73,
	0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x44, 0x22, 0x8d, 0x01,
	0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x2f, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x13, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x3b, 0x0a, 0x08, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x43, 0x6f,
	0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x08, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x22, 0x4b, 0x0a,
	0x15, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x46, 0x6f,
	0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x49, 0x6e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x49, 0x6e, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x08, 0x48,
	0x54, 0x4d, 0x4c, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x73, 0x63, 0x65, 0x6e,
	0x61, 0x72, 0x69, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x08,
	0x6e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x66, 0x6f, 0x72, 0x6d,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x63, 0x65,
	0x6e, 0x61, 0x72, 0x69, 0x6f, 0x2e, 0x48, 0x54, 0x4d, 0x4c, 0x4e, 0x6f, 0x64, 0x65, 0x46, 0x6f,
	0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x66, 0x0a, 0x10, 0x48, 0x54, 0x4d, 0x4c, 0x4e, 0x6f, 0x64, 0x65, 0x46, 0x6f, 0x72, 0x6d,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x49, 0x6e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x74, 0x6d, 0x6c,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x68, 0x74,
	0x6d, 0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x2a, 0x54, 0x0a, 0x09, 0x4e, 0x6f, 0x64, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x46, 0x4f, 0x52, 0x4d, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4e, 0x44, 0x49,
	0x54, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x56, 0x41, 0x52, 0x49, 0x41, 0x42,
	0x4c, 0x45, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x54, 0x4d, 0x4c, 0x10, 0x05, 0x42, 0x0d,
	0x5a, 0x0b, 0x67, 0x6f, 0x2f, 0x73, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_scenario_proto_rawDescOnce sync.Once
	file_scenario_proto_rawDescData = file_scenario_proto_rawDesc
)

func file_scenario_proto_rawDescGZIP() []byte {
	file_scenario_proto_rawDescOnce.Do(func() {
		file_scenario_proto_rawDescData = protoimpl.X.CompressGZIP(file_scenario_proto_rawDescData)
	})
	return file_scenario_proto_rawDescData
}

var file_scenario_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_scenario_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_scenario_proto_goTypes = []interface{}{
	(NodeTypes)(0),                // 0: scenario.NodeTypes
	(*MessageNode)(nil),           // 1: scenario.MessageNode
	(*MessageNodeFormData)(nil),   // 2: scenario.MessageNodeFormData
	(*FormNode)(nil),              // 3: scenario.FormNode
	(*FormNodeFormData)(nil),      // 4: scenario.FormNodeFormData
	(*VariableNode)(nil),          // 5: scenario.VariableNode
	(*VariableNodeFormData)(nil),  // 6: scenario.VariableNodeFormData
	(*ConditionNode)(nil),         // 7: scenario.ConditionNode
	(*ConditionNodeFormData)(nil), // 8: scenario.ConditionNodeFormData
	(*HTMLNode)(nil),              // 9: scenario.HTMLNode
	(*HTMLNodeFormData)(nil),      // 10: scenario.HTMLNodeFormData
}
var file_scenario_proto_depIdxs = []int32{
	0,  // 0: scenario.MessageNode.nodeType:type_name -> scenario.NodeTypes
	2,  // 1: scenario.MessageNode.formData:type_name -> scenario.MessageNodeFormData
	0,  // 2: scenario.FormNode.nodeType:type_name -> scenario.NodeTypes
	4,  // 3: scenario.FormNode.formData:type_name -> scenario.FormNodeFormData
	0,  // 4: scenario.VariableNode.nodeType:type_name -> scenario.NodeTypes
	6,  // 5: scenario.VariableNode.formData:type_name -> scenario.VariableNodeFormData
	0,  // 6: scenario.ConditionNode.nodeType:type_name -> scenario.NodeTypes
	8,  // 7: scenario.ConditionNode.formData:type_name -> scenario.ConditionNodeFormData
	0,  // 8: scenario.HTMLNode.nodeType:type_name -> scenario.NodeTypes
	10, // 9: scenario.HTMLNode.formData:type_name -> scenario.HTMLNodeFormData
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_scenario_proto_init() }
func file_scenario_proto_init() {
	if File_scenario_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_scenario_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scenario_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageNodeFormData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scenario_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scenario_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormNodeFormData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scenario_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VariableNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scenario_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VariableNodeFormData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scenario_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConditionNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scenario_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConditionNodeFormData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scenario_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTMLNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scenario_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTMLNodeFormData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scenario_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scenario_proto_goTypes,
		DependencyIndexes: file_scenario_proto_depIdxs,
		EnumInfos:         file_scenario_proto_enumTypes,
		MessageInfos:      file_scenario_proto_msgTypes,
	}.Build()
	File_scenario_proto = out.File
	file_scenario_proto_rawDesc = nil
	file_scenario_proto_goTypes = nil
	file_scenario_proto_depIdxs = nil
}
