// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: workflow.proto

package workflow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomNodeTypeName int32

const (
	CustomNodeTypeName_BLANK     CustomNodeTypeName = 0
	CustomNodeTypeName_START     CustomNodeTypeName = 1
	CustomNodeTypeName_MESSAGE   CustomNodeTypeName = 2
	CustomNodeTypeName_RESIZABLE CustomNodeTypeName = 3
	CustomNodeTypeName_CONDITION CustomNodeTypeName = 4
	CustomNodeTypeName_CODE      CustomNodeTypeName = 5
	CustomNodeTypeName_VARIABLE  CustomNodeTypeName = 6
	CustomNodeTypeName_HTML      CustomNodeTypeName = 8
)

// Enum value maps for CustomNodeTypeName.
var (
	CustomNodeTypeName_name = map[int32]string{
		0: "BLANK",
		1: "START",
		2: "MESSAGE",
		3: "RESIZABLE",
		4: "CONDITION",
		5: "CODE",
		6: "VARIABLE",
		8: "HTML",
	}
	CustomNodeTypeName_value = map[string]int32{
		"BLANK":     0,
		"START":     1,
		"MESSAGE":   2,
		"RESIZABLE": 3,
		"CONDITION": 4,
		"CODE":      5,
		"VARIABLE":  6,
		"HTML":      8,
	}
)

func (x CustomNodeTypeName) Enum() *CustomNodeTypeName {
	p := new(CustomNodeTypeName)
	*p = x
	return p
}

func (x CustomNodeTypeName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CustomNodeTypeName) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_proto_enumTypes[0].Descriptor()
}

func (CustomNodeTypeName) Type() protoreflect.EnumType {
	return &file_workflow_proto_enumTypes[0]
}

func (x CustomNodeTypeName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CustomNodeTypeName.Descriptor instead.
func (CustomNodeTypeName) EnumDescriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

// Message Node
// ----------------------------------------------------------------------------------------------------
type MessageNodeDataType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Text  string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *MessageNodeDataType) Reset() {
	*x = MessageNodeDataType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageNodeDataType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageNodeDataType) ProtoMessage() {}

func (x *MessageNodeDataType) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageNodeDataType.ProtoReflect.Descriptor instead.
func (*MessageNodeDataType) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *MessageNodeDataType) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MessageNodeDataType) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Resizable Node
type ResizableNodeDataType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Text  string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ResizableNodeDataType) Reset() {
	*x = ResizableNodeDataType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResizableNodeDataType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizableNodeDataType) ProtoMessage() {}

func (x *ResizableNodeDataType) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizableNodeDataType.ProtoReflect.Descriptor instead.
func (*ResizableNodeDataType) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *ResizableNodeDataType) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ResizableNodeDataType) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Condition Node
// ----------------------------------------------------------------------------------------------------
type ConditionNodeDataType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string                             `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Items []*ConditionNodeDataType_ItemsType `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ConditionNodeDataType) Reset() {
	*x = ConditionNodeDataType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConditionNodeDataType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionNodeDataType) ProtoMessage() {}

func (x *ConditionNodeDataType) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionNodeDataType.ProtoReflect.Descriptor instead.
func (*ConditionNodeDataType) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *ConditionNodeDataType) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ConditionNodeDataType) GetItems() []*ConditionNodeDataType_ItemsType {
	if x != nil {
		return x.Items
	}
	return nil
}

// Code Node
// ----------------------------------------------------------------------------------------------------
type CodeNodeDataType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *CodeNodeDataType) Reset() {
	*x = CodeNodeDataType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodeNodeDataType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeNodeDataType) ProtoMessage() {}

func (x *CodeNodeDataType) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeNodeDataType.ProtoReflect.Descriptor instead.
func (*CodeNodeDataType) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *CodeNodeDataType) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// Variable Node
// ----------------------------------------------------------------------------------------------------
type VariableNodeDataType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string                            `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Items []*VariableNodeDataType_ItemsType `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *VariableNodeDataType) Reset() {
	*x = VariableNodeDataType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VariableNodeDataType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableNodeDataType) ProtoMessage() {}

func (x *VariableNodeDataType) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableNodeDataType.ProtoReflect.Descriptor instead.
func (*VariableNodeDataType) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *VariableNodeDataType) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VariableNodeDataType) GetItems() []*VariableNodeDataType_ItemsType {
	if x != nil {
		return x.Items
	}
	return nil
}

// HTML Node
// ----------------------------------------------------------------------------------------------------
type HTMLNodeDataType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Text  string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *HTMLNodeDataType) Reset() {
	*x = HTMLNodeDataType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTMLNodeDataType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTMLNodeDataType) ProtoMessage() {}

func (x *HTMLNodeDataType) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTMLNodeDataType.ProtoReflect.Descriptor instead.
func (*HTMLNodeDataType) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *HTMLNodeDataType) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HTMLNodeDataType) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ConditionNodeDataType_ItemsType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Text  string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ConditionNodeDataType_ItemsType) Reset() {
	*x = ConditionNodeDataType_ItemsType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConditionNodeDataType_ItemsType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionNodeDataType_ItemsType) ProtoMessage() {}

func (x *ConditionNodeDataType_ItemsType) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionNodeDataType_ItemsType.ProtoReflect.Descriptor instead.
func (*ConditionNodeDataType_ItemsType) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ConditionNodeDataType_ItemsType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ConditionNodeDataType_ItemsType) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ConditionNodeDataType_ItemsType) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type VariableNodeDataType_ItemsType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are assignable to Value:
	//
	//	*VariableNodeDataType_ItemsType_BooleanValue
	//	*VariableNodeDataType_ItemsType_StringValue
	//	*VariableNodeDataType_ItemsType_IntValue
	//	*VariableNodeDataType_ItemsType_FloatValue
	Value isVariableNodeDataType_ItemsType_Value `protobuf_oneof:"value"`
}

func (x *VariableNodeDataType_ItemsType) Reset() {
	*x = VariableNodeDataType_ItemsType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workflow_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VariableNodeDataType_ItemsType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableNodeDataType_ItemsType) ProtoMessage() {}

func (x *VariableNodeDataType_ItemsType) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableNodeDataType_ItemsType.ProtoReflect.Descriptor instead.
func (*VariableNodeDataType_ItemsType) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{4, 0}
}

func (x *VariableNodeDataType_ItemsType) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VariableNodeDataType_ItemsType) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (m *VariableNodeDataType_ItemsType) GetValue() isVariableNodeDataType_ItemsType_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *VariableNodeDataType_ItemsType) GetBooleanValue() bool {
	if x, ok := x.GetValue().(*VariableNodeDataType_ItemsType_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

func (x *VariableNodeDataType_ItemsType) GetStringValue() string {
	if x, ok := x.GetValue().(*VariableNodeDataType_ItemsType_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *VariableNodeDataType_ItemsType) GetIntValue() int32 {
	if x, ok := x.GetValue().(*VariableNodeDataType_ItemsType_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (x *VariableNodeDataType_ItemsType) GetFloatValue() float32 {
	if x, ok := x.GetValue().(*VariableNodeDataType_ItemsType_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

type isVariableNodeDataType_ItemsType_Value interface {
	isVariableNodeDataType_ItemsType_Value()
}

type VariableNodeDataType_ItemsType_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,3,opt,name=booleanValue,proto3,oneof"` // 布尔类型
}

type VariableNodeDataType_ItemsType_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=stringValue,proto3,oneof"` // 字符串类型
}

type VariableNodeDataType_ItemsType_IntValue struct {
	IntValue int32 `protobuf:"varint,5,opt,name=intValue,proto3,oneof"` // 整数类型
}

type VariableNodeDataType_ItemsType_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,6,opt,name=floatValue,proto3,oneof"` // 浮点数类型
}

func (*VariableNodeDataType_ItemsType_BooleanValue) isVariableNodeDataType_ItemsType_Value() {}

func (*VariableNodeDataType_ItemsType_StringValue) isVariableNodeDataType_ItemsType_Value() {}

func (*VariableNodeDataType_ItemsType_IntValue) isVariableNodeDataType_ItemsType_Value() {}

func (*VariableNodeDataType_ItemsType_FloatValue) isVariableNodeDataType_ItemsType_Value() {}

var File_workflow_proto protoreflect.FileDescriptor

var file_workflow_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x22, 0x3f, 0x0a, 0x13, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x41, 0x0a, 0x15, 0x52,
	0x65, 0x73, 0x69, 0x7a, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0xb5,
	0x01, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x3f,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a,
	0x45, 0x0a, 0x09, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x28, 0x0a, 0x10, 0x43, 0x6f, 0x64, 0x65, 0x4e, 0x6f,
	0x64, 0x65, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x22, 0xaf, 0x02, 0x0a, 0x14, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x64,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x3e, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28,
	0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a,
	0xc0, 0x01, 0x0a, 0x09, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x24, 0x0a, 0x0c, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0c, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x22, 0x0a, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x08, 0x69, 0x6e, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x69,
	0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x0a, 0x66,
	0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x3c, 0x0a, 0x10, 0x48, 0x54, 0x4d, 0x4c, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x2a, 0x77, 0x0a, 0x12, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x4c, 0x41, 0x4e, 0x4b, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07,
	0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x53,
	0x49, 0x5a, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4e, 0x44,
	0x49, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x4f, 0x44, 0x45, 0x10,
	0x05, 0x12, 0x0c, 0x0a, 0x08, 0x56, 0x41, 0x52, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x06, 0x12,
	0x08, 0x0a, 0x04, 0x48, 0x54, 0x4d, 0x4c, 0x10, 0x08, 0x42, 0x0d, 0x5a, 0x0b, 0x67, 0x6f, 0x2f,
	0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_workflow_proto_rawDescOnce sync.Once
	file_workflow_proto_rawDescData = file_workflow_proto_rawDesc
)

func file_workflow_proto_rawDescGZIP() []byte {
	file_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(file_workflow_proto_rawDescData)
	})
	return file_workflow_proto_rawDescData
}

var file_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_workflow_proto_goTypes = []interface{}{
	(CustomNodeTypeName)(0),                 // 0: workflow.CustomNodeTypeName
	(*MessageNodeDataType)(nil),             // 1: workflow.MessageNodeDataType
	(*ResizableNodeDataType)(nil),           // 2: workflow.ResizableNodeDataType
	(*ConditionNodeDataType)(nil),           // 3: workflow.ConditionNodeDataType
	(*CodeNodeDataType)(nil),                // 4: workflow.CodeNodeDataType
	(*VariableNodeDataType)(nil),            // 5: workflow.VariableNodeDataType
	(*HTMLNodeDataType)(nil),                // 6: workflow.HTMLNodeDataType
	(*ConditionNodeDataType_ItemsType)(nil), // 7: workflow.ConditionNodeDataType.ItemsType
	(*VariableNodeDataType_ItemsType)(nil),  // 8: workflow.VariableNodeDataType.ItemsType
}
var file_workflow_proto_depIdxs = []int32{
	7, // 0: workflow.ConditionNodeDataType.items:type_name -> workflow.ConditionNodeDataType.ItemsType
	8, // 1: workflow.VariableNodeDataType.items:type_name -> workflow.VariableNodeDataType.ItemsType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_workflow_proto_init() }
func file_workflow_proto_init() {
	if File_workflow_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_workflow_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageNodeDataType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflow_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResizableNodeDataType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflow_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConditionNodeDataType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflow_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodeNodeDataType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflow_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VariableNodeDataType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflow_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTMLNodeDataType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflow_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConditionNodeDataType_ItemsType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workflow_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VariableNodeDataType_ItemsType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_workflow_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*VariableNodeDataType_ItemsType_BooleanValue)(nil),
		(*VariableNodeDataType_ItemsType_StringValue)(nil),
		(*VariableNodeDataType_ItemsType_IntValue)(nil),
		(*VariableNodeDataType_ItemsType_FloatValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_workflow_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_proto_depIdxs,
		EnumInfos:         file_workflow_proto_enumTypes,
		MessageInfos:      file_workflow_proto_msgTypes,
	}.Build()
	File_workflow_proto = out.File
	file_workflow_proto_rawDesc = nil
	file_workflow_proto_goTypes = nil
	file_workflow_proto_depIdxs = nil
}
