# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workflow.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eworkflow.proto\x12\x08workflow\"2\n\x13MessageNodeDataType\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"4\n\x15ResizableNodeDataType\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x96\x01\n\x15\x43onditionNodeDataType\x12\r\n\x05title\x18\x01 \x01(\t\x12\x38\n\x05items\x18\x02 \x03(\x0b\x32).workflow.ConditionNodeDataType.ItemsType\x1a\x34\n\tItemsType\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\"!\n\x10\x43odeNodeDataType\x12\r\n\x05title\x18\x01 \x01(\t\"\xe7\x01\n\x14VariableNodeDataType\x12\r\n\x05title\x18\x01 \x01(\t\x12\x37\n\x05items\x18\x02 \x03(\x0b\x32(.workflow.VariableNodeDataType.ItemsType\x1a\x86\x01\n\tItemsType\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x16\n\x0c\x62ooleanValue\x18\x03 \x01(\x08H\x00\x12\x15\n\x0bstringValue\x18\x04 \x01(\tH\x00\x12\x12\n\x08intValue\x18\x05 \x01(\x05H\x00\x12\x14\n\nfloatValue\x18\x06 \x01(\x02H\x00\x42\x07\n\x05value\"/\n\x10HTMLNodeDataType\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t*w\n\x12\x43ustomNodeTypeName\x12\t\n\x05\x42LANK\x10\x00\x12\t\n\x05START\x10\x01\x12\x0b\n\x07MESSAGE\x10\x02\x12\r\n\tRESIZABLE\x10\x03\x12\r\n\tCONDITION\x10\x04\x12\x08\n\x04\x43ODE\x10\x05\x12\x0c\n\x08VARIABLE\x10\x06\x12\x08\n\x04HTML\x10\x08\x42\rZ\x0bgo/workflowb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workflow_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013go/workflow'
  _globals['_CUSTOMNODETYPENAME']._serialized_start=605
  _globals['_CUSTOMNODETYPENAME']._serialized_end=724
  _globals['_MESSAGENODEDATATYPE']._serialized_start=28
  _globals['_MESSAGENODEDATATYPE']._serialized_end=78
  _globals['_RESIZABLENODEDATATYPE']._serialized_start=80
  _globals['_RESIZABLENODEDATATYPE']._serialized_end=132
  _globals['_CONDITIONNODEDATATYPE']._serialized_start=135
  _globals['_CONDITIONNODEDATATYPE']._serialized_end=285
  _globals['_CONDITIONNODEDATATYPE_ITEMSTYPE']._serialized_start=233
  _globals['_CONDITIONNODEDATATYPE_ITEMSTYPE']._serialized_end=285
  _globals['_CODENODEDATATYPE']._serialized_start=287
  _globals['_CODENODEDATATYPE']._serialized_end=320
  _globals['_VARIABLENODEDATATYPE']._serialized_start=323
  _globals['_VARIABLENODEDATATYPE']._serialized_end=554
  _globals['_VARIABLENODEDATATYPE_ITEMSTYPE']._serialized_start=420
  _globals['_VARIABLENODEDATATYPE_ITEMSTYPE']._serialized_end=554
  _globals['_HTMLNODEDATATYPE']._serialized_start=556
  _globals['_HTMLNODEDATATYPE']._serialized_end=603
# @@protoc_insertion_point(module_scope)
