// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v4.25.2
// source: chat.proto

/* eslint-disable */

export const protobufPackage = "notes";

export interface UserData {
  id: string;
  name: string;
  email: string;
  avatarUrl: string;
}

export interface ChatMessage {
  content: string;
  /** ISO 8601 string format for timestamp */
  timestamp: string;
  /** ID of the member sending the message */
  memberId: string;
}

export interface ChatRoom {
  /** Unique ID for the chat room */
  id: string;
  /** Name of the chat room */
  name: string;
  /** Member data */
  member:
    | UserData
    | undefined;
  /** List of chat messages */
  messages: ChatMessage[];
}
