// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v4.25.2
// source: notes.proto

/* eslint-disable */

export const protobufPackage = "notes";

export enum SelectableNoteType {
  RAFT = 0,
  UNRECOGNIZED = -1,
}

export interface NoteDataType {
  Id: string;
  type: SelectableNoteType;
  title: string;
  message: string;
  createdAt: string;
  updatedAt: string;
}
