// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v4.25.2
// source: notes.proto

/* eslint-disable */

export const protobufPackage = "notes";

export enum SelectableNoteType {
  ALL = 0,
  RAFT = 1,
  UNRECOGNIZED = -1,
}

export enum AccountRoleType {
  NORMAL = 0,
  ADMIN = 1,
  UNRECOGNIZED = -1,
}

export interface NoteDataType {
  Id: string;
  type: SelectableNoteType;
  title: string;
  message: string;
  createdAt: string;
  updatedAt: string;
  accountId: string;
}

export interface AccountDataType {
  Id: string;
  displayName: string;
  password: string;
  email: string;
  avatar: string;
  createdAt: string;
  updatedAt: string;
  role: AccountRoleType;
  isActive: boolean;
}
