// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v4.25.2
// source: workflow.proto

/* eslint-disable */

export const protobufPackage = "workflow";

export enum CustomNodeTypeName {
  BLANK = 0,
  START = 1,
  MESSAGE = 2,
  RESIZABLE = 3,
  CONDITION = 4,
  CODE = 5,
  VARIABLE = 6,
  HTML = 8,
  UNRECOGNIZED = -1,
}

/**
 * Message Node
 * ----------------------------------------------------------------------------------------------------
 */
export interface MessageNodeDataType {
  title: string;
  text: string;
}

/** Resizable Node */
export interface ResizableNodeDataType {
  title: string;
  text: string;
}

/**
 * Condition Node
 * ----------------------------------------------------------------------------------------------------
 */
export interface ConditionNodeDataType {
  title: string;
  items: ConditionNodeDataType_ItemsType[];
}

export interface ConditionNodeDataType_ItemsType {
  id: number;
  title: string;
  text: string;
}

/**
 * Code Node
 * ----------------------------------------------------------------------------------------------------
 */
export interface CodeNodeDataType {
  title: string;
}

/**
 * Variable Node
 * ----------------------------------------------------------------------------------------------------
 */
export interface VariableNodeDataType {
  title: string;
  items: VariableNodeDataType_ItemsType[];
}

export interface VariableNodeDataType_ItemsType {
  id: number;
  key: string;
  /** 布尔类型 */
  booleanValue?:
    | boolean
    | undefined;
  /** 字符串类型 */
  stringValue?:
    | string
    | undefined;
  /** 整数类型 */
  intValue?:
    | number
    | undefined;
  /** 浮点数类型 */
  floatValue?: number | undefined;
}

/**
 * HTML Node
 * ----------------------------------------------------------------------------------------------------
 */
export interface HTMLNodeDataType {
  title: string;
  text: string;
}
